name: aetherbloom
description: A medication reminder and tracking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Removed to avoid Android SDK conflicts:
  # shared_preferences: ^2.2.2
  # http: ^1.3.0
  # fl_chart: ^0.68.0
  # intl: ^0.19.0
  # uuid: ^4.5.1
  # flutter_blue_plus: ^1.35.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/