// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBJBZw9pDufAHIUqeB7ahPdunKfA26XY',
    appId: '1:393508175029:android:fc11c7b1a70f035d7dd2fc',
    messagingSenderId: '393508175029',
    projectId: 'aetherbloomapp',
    storageBucket: 'aetherbloomapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe_WJp2cfpxoe_XDzBpgQo0PberIE6BXc',
    appId: '1:393508175029:ios:712b20ca324e9fc37dd2fc',
    messagingSenderId: '393508175029',
    projectId: 'aetherbloomapp',
    storageBucket: 'aetherbloomapp.firebasestorage.app',
    iosBundleId: 'com.example.projectAetherbloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe_WJp2cfpxoe_XDzBpgQo0PberIE6BXc',
    appId: '1:393508175029:ios:82830ca64b921f227dd2fc',
    messagingSenderId: '393508175029',
    projectId: 'aetherbloomapp',
    storageBucket: 'aetherbloomapp.firebasestorage.app',
    iosBundleId: 'com.example.projectAe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4tAeEA9jx-Ssz2fhHF8iXLpfoHQW3Lqs',
    appId: '1:393508175029:web:7222352e96f1f6d47dd2fc',
    messagingSenderId: '393508175029',
    projectId: 'aetherbloomapp',
    authDomain: 'aetherbloomapp.firebaseapp.com',
    storageBucket: 'aetherbloomapp.firebasestorage.app',
    measurementId: 'G-11B84CLV9F',
  );
}
